In [2]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

In [3]:
from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')

In [4]:
# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #Detecing the face
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    #Cropping the face to focus on the faces only
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-4-08bf85c8d9c6>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [5]:
video_capture = cv2.VideoCapture(0)
while True:
  # Capturing the Video
    _, frame = video_capture.read()
    
    #Extracting Cropped Face
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        #Resizing the Images
        face = cv2.resize(face, (224, 224)) #Resizing into 224x224 because we trained the model with this image size.
        im = Image.fromarray(face, 'RGB')
        #Forming a array with Image and RGB values giving a dimeneion of 224x224x3
        img_array = np.array(im)
        #Our keras model used a 4D tensor, (images x height x width x channel)
        #So changing dimension 224x224x3 into 1x224x224x3
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"

        #Predicting the name according which have the highest prediction values in the class
        finalpred = max(pred[0][0],pred[0][1])
        
        if(pred[0][0]== finalpred):
            name='Jai'
        if(pred[0][1]== finalpred):
          name='Parth'
        #Putting a Frame over the face with the name on it
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    #Showing the output
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()


[[1.0000000e+00 5.7440374e-28]]
[[1. 0.]]
[[1.000000e+00 2.061097e-33]]
[[1.000000e+00 2.563481e-34]]
[[1.0000000e+00 8.1516535e-30]]
[[9.9999976e-01 2.7605094e-07]]
[[1.000000e+00 8.362225e-25]]
[[1.0000000e+00 6.0762172e-30]]
[[1.0000000e+00 3.1855957e-35]]
[[1.0000000e+00 3.6389647e-36]]
[[1.000000e+00 8.663446e-27]]
[[1.0000000e+00 1.0742907e-27]]
[[1.0000000e+00 2.3562982e-19]]
[[1.0000000e+00 3.6245013e-36]]
[[1.000000e+00 4.735295e-34]]
[[1.000000e+00 7.742465e-27]]
[[1.0000000e+00 1.3660021e-25]]
[[1.000000e+00 7.019488e-34]]
[[1.0000000e+00 6.2454184e-30]]
[[1.0000000e+00 6.5972985e-25]]
[[1.000000e+00 9.811861e-23]]
[[1.0000000e+00 3.7792554e-26]]
[[1. 0.]]
[[1.000000e+00 2.560646e-27]]
[[1.000000e+00 2.790701e-26]]
[[1.0000000e+00 3.1421806e-29]]
[[1.000000e+00 7.477426e-26]]
[[1.000000e+00 6.734656e-26]]
[[1.0000000e+00 4.9449836e-37]]
[[1.00000e+00 8.92492e-21]]
[[1.0000000e+00 4.2468245e-36]]
[[1.0000000e+00 6.9773354e-26]]
[[1.0000000e+00 1.0814245e-27]]
[[1.0000000e+00 

KeyboardInterrupt: 